// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305003928_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Vestuário",
                            Description = "Camiseta 100% algodão com estampa de código de programação",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/2_no_internet.jpg?raw=true",
                            Name = "Camiseta Geek Code",
                            Price = 69.90m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Acessórios",
                            Description = "Caneca de porcelana com capacidade de 350ml tema Star Wars",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/3_vader.jpg?raw=true",
                            Name = "Caneca Star Wars Darth Vader",
                            Price = 39.90m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Colecionáveis",
                            Description = "Action figure colecionável do personagem Grogu (Baby Yoda) 15cm",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/5_100_doctor.jpg?raw=true",
                            Name = "Action Figure Baby Yoda",
                            Price = 189.90m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Periféricos",
                            Description = "Mouse gamer com iluminação RGB, 7 botões programáveis e 16000 DPI",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/6_spaceship.jpg?raw=true",
                            Name = "Mouse Gamer RGB",
                            Price = 149.90m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Periféricos",
                            Description = "Teclado mecânico com switches blue, iluminação RGB personalizável",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/7_robot.jpg?raw=true",
                            Name = "Teclado Mecânico RGB",
                            Price = 299.90m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Periféricos",
                            Description = "Headset gamer com som surround 7.1, microfone removível e LED RGB",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/8_chess.jpg?raw=true",
                            Name = "Headset Gamer 7.1",
                            Price = 249.90m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Colecionáveis",
                            Description = "Boneco colecionável Funko Pop do Batman da DC Comics",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/9_comic_book.jpg?raw=true",
                            Name = "Funko Pop Batman",
                            Price = 89.90m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Acessórios",
                            Description = "Mochila para laptop até 17 polegadas com compartimentos para periféricos",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/10_shirt.jpg?raw=true",
                            Name = "Mochila Laptop Gamer",
                            Price = 179.90m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Livros",
                            Description = "Livro Clean Code de Robert C. Martin - Guia para código limpo",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/11_book.jpg?raw=true",
                            Name = "Livro Clean Code",
                            Price = 79.90m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Periféricos",
                            Description = "Webcam com resolução Full HD 1080p, microfone embutido e foco automático",
                            ImageUrl = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/12_space_suit.jpg?raw=true",
                            Name = "Webcam Full HD 1080p",
                            Price = 199.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
